version: '3'

services:
  db_postgresql:
    container_name: db_postgresql_local
    image: postgres
    restart: always
    volumes:
      - ./db_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootsecret
    ports:
      - 5433:5432

  db_mysql:
    container_name: db_mysql_local
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - ./db_mysql:/var/lib/mysql